services:
  - type: web
    name: abitare-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: abitare-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d

databases:
  - name: abitare-db
    databaseName: abitare
    user: abitare-user
    plan: free
    ipAllowList:
      - 0.0.0.0/0
